#ifndef KB_READER_H
#define KB_READER_H

#include <Arduino.h>
#include <LittleFS.h>

class KBReader {
  public:
    KBReader();
    ~KBReader();

    // Opens a .kmb comic file generated by the KomaBon Web Converter
    bool open(const char* path);
    void close();

    // Comic Metadata Retrieval
    uint16_t getWidth() const {
        return _width;
    }
    uint16_t getHeight() const {
        return _height;
    }
    uint16_t getPageCount() const {
        return _pageCount;
    }

    // Cover Management
    bool hasCover() const {
        return _coverLen > 0;
    }
    bool getCover(uint8_t* buffer, size_t bufferSize);

    // Page Reading - Direct Access
    // Populates the given pre-allocated buffer with uncompressed 1-bit MSB pixel data
    bool readPage(uint16_t index, uint8_t* buffer);

  private:
    File _file;

    // Parsed structural parameters
    uint16_t _width;
    uint16_t _height;
    uint16_t _pageCount;
    uint32_t _coverLen;

    // Direct memory addressing offsets
    uint32_t _coverOffset;
    uint32_t _dataOffset;
};

#endif // KB_READER_H